---
version: '2'
services:
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - "/mnt/MEDIA/appdata/nzbget:/config"
      - "/mnt/MEDIA/Downloads:/downloads"
      - "/mnt/MEDIA/Downloads/complete:/downloads/complete"
    ports:
      - 27020:6789
    restart: unless-stopped
    environment:
      - PUID=500
      - PGID=100
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - nzbget
    volumes:
      - "/mnt/MEDIA/appdata/sonarr:/config"
      - "/mnt/MEDIA/TV:/tv"
      - "/mnt/MEDIA/Downloads/complete/Series:/downloads"
    ports:
      - 27021:8989
    links:
      - nzbget
    restart: unless-stopped
    environment:
      - PUID=500
      - PGID=100
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    depends_on:
      - nzbget
    volumes:
      - "/mnt/MEDIA/appdata/radarr:/config"
      - "/mnt/MEDIA/Movies:/movies"
      - "/mnt/MEDIA/Downloads/complete/Movies:/downloads"
    ports:
      - 27022:7878
    links:
      - nzbget
    restart: unless-stopped
    environment:
      - PUID=500
      - PGID=100
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    volumes:
      - "/home/tim/PlexConfig:/config"
      - "/mnt/MEDIA/Transcode:/transcode"
      - "/mnt/MEDIA:/data"
    restart: unless-stopped
    network_mode: host
    hostname: fairweatherflix
    environment:
      - TZ="America/Eastern"
      - PUID=500
      - PGID=100
  # portainer:
  #   image: portainer/portainer
  #   container_name: portainer
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - "./portainer:/data portainer/portainer"
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   restart:
  #     unless-stopped
  # couchpotato:
  #   image: linuxserver/couchpotato
  #   container_name: couchpotato
  #   depends_on:
  #     - nzbget
  #   volumes:
  #     - "/mnt/MEDIA/appdata/couchpotato:/config"
  #     - "/mnt/MEDIA/Finished:/downloads"
  #     - "/mnt/MEDIA/Movies:/movies"
  #   ports:
  #     - 27023:5050
  #   links:
  #     - nzbget
  #   restart: unless-stopped
  #   environment:
  #     - PUID=20
  #     - PGID=501
